---
title: "R beginner workshop - Pacific Science Enterprise Centre (PSEC) Data Management and Analysis group"
author: Ania Posacka & Evan Henderson
date: "February 26, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Welcome PSEC scientists!  


The goal of PSEC Data Management and Analysis group is to bring together scientists in the facility who are interested in collaboratively maintaining, improving, and developing data management and analysis skills. Our sessions provide a forum for continued professional growth through sharing, learning, and mentorship related to data collection, data management, and data analysis.

To start with, we are holding two extended sessions (3 hours each) as a crash-course in the basics of R and its graphical user interface, R Studio. We also share practices for a scientific study design and analysis workflow with R. Here you can find materials from these sessions and links to resources to further your learning.

Materials from our workshops are various online tutorials & advice from these sources

* [R for Ecology by Data Carpentry](http://www.datacarpentry.org/R-ecology-lesson/) by [Data Carpentry](http://www.datacarpentry.org/)
* [R for Data Science](http://r4ds.had.co.nz/introduction.html) by [Hadley Wickham](http://hadley.nz/) and [Garret Grolemund](https://www.datacamp.com/instructors/garrettgrolemund)
* [STAT545 @ UBC](http://stat545.com/): Data wrangling, exploration, and analysis with R by [Jenny Bryan](https://github.com/jennybc)


> Prerequists

Install R and RStudio, click on this link for instructions from STAT454

Day 1| Wednesday 28th Feb:
Do this before:

● Reinforcement of objective-driven and organized data science: what to do before you
even have your data
o Objectives and ‘working backwards’
o Database naming and structure
o File naming and version control
● RStudio orientation & best practices for organizing your analysis [workspace, R projects].
● Documenting your analysis: quick intro into RMarkdown
● Creating variables
● Data types in R and coding basics
● What is a data frame, creating one & getting basic info about it
Session 2: Exploratory Data Analysis | Intro to dplyr & ggplot (3 hrs)
● Finding, transforming & extracting data
● Getting summary statistics & other calculations from a dataset
● Adding new variables to your dataset
● Importing data (CSV)
● Ggplot basics
● Missing values & outliers